# Generated by Django 5.2.10 on 2026-01-16 04:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('department', models.CharField(blank=True, choices=[('HR', 'Human Resources'), ('Engineering', 'Engineering'), ('Sales', 'Sales'), ('Marketing', 'Marketing'), ('Finance', 'Finance')], max_length=50, null=True)),
                ('role', models.CharField(blank=True, choices=[('Manager', 'Manager'), ('Developer', 'Developer'), ('Analyst', 'Analyst'), ('Designer', 'Designer'), ('Consultant', 'Consultant')], max_length=50, null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['email'], name='employees_e_email_8f5bbc_idx'), models.Index(fields=['department'], name='employees_e_departm_e28f46_idx'), models.Index(fields=['role'], name='employees_e_role_caa0a5_idx')],
            },
        ),
    ]
